# Generated by Django 5.0.6 on 2025-02-13 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_pc', models.CharField(max_length=155, unique=True)),
                ('num_invetario', models.IntegerField()),
                ('marca', models.CharField(max_length=155, unique=True)),
                ('estado', models.CharField(max_length=10)),
                ('numero_pc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departameto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('cantidad_pc', models.IntegerField()),
                ('computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invetario.computadora')),
            ],
        ),
        migrations.CreateModel(
            name='Invetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invetario.departameto')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invetario.computadora')),
            ],
        ),
    ]
