# Generated by Django 5.0.6 on 2025-02-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='componente_pc',
            field=models.CharField(max_length=155),
        ),
    ]
