# Generated by Django 5.0.6 on 2025-02-13 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0002_alter_computadora_componente_pc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computadora',
            old_name='num_invetario',
            new_name='num_inventario',
        ),
    ]
