# Generated by Django 5.0.6 on 2025-02-21 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0003_rename_num_invetario_computadora_num_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departameto',
            name='computadora',
        ),
        migrations.AddField(
            model_name='computadora',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invetario.departameto'),
            preserve_default=False,
        ),
    ]
