# Generated by Django 5.0.6 on 2025-02-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0004_remove_departameto_computadora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='marca',
            field=models.CharField(max_length=155),
        ),
    ]
