# Generated by Django 5.0.6 on 2025-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0005_alter_computadora_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procesador', models.CharField(max_length=255)),
                ('memoria_ram', models.IntegerField()),
                ('disco', models.CharField(max_length=255)),
                ('gpu', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
