# Generated by Django 5.0.6 on 2025-03-05 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0006_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='computadora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invetario.computadora'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='memoria_ram',
            field=models.CharField(max_length=255),
        ),
    ]
