# Generated by Django 5.0.6 on 2025-03-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0007_propiedad_computadora_alter_propiedad_memoria_ram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=255)),
                ('capacidad', models.IntegerField()),
                ('marca', models.CharField(max_length=155)),
                ('serie', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LectoresCD_DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='MemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=4)),
                ('capacidad', models.IntegerField()),
                ('marca', models.CharField(max_length=155)),
                ('velocidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mensaje', models.TextField(max_length=300)),
            ],
        ),
    ]
