# Generated by Django 5.0.6 on 2025-03-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetario', '0008_discos_lectorescd_dvd_memoriaram_mensajes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectoresCD_DVD',
            new_name='LectorCD_DVD',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='disco',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='memoria_ram',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lector',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invetario.lectorcd_dvd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lista_discos_duros',
            field=models.ManyToManyField(to='invetario.discos'),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='lista_memorias_ram',
            field=models.ManyToManyField(to='invetario.memoriaram'),
        ),
        migrations.DeleteModel(
            name='Invetario',
        ),
    ]
